# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'snipeassist.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDateEdit,
    QGroupBox, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(850, 636)
        self.action_Exit = QAction(MainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName(u"action_Save")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBoxRequired = QGroupBox(self.centralwidget)
        self.groupBoxRequired.setObjectName(u"groupBoxRequired")
        self.groupBoxRequired.setGeometry(QRect(10, 0, 831, 71))
        self.labelCompany = QLabel(self.groupBoxRequired)
        self.labelCompany.setObjectName(u"labelCompany")
        self.labelCompany.setGeometry(QRect(10, 10, 71, 16))
        self.comboBoxCompany = QComboBox(self.groupBoxRequired)
        self.comboBoxCompany.setObjectName(u"comboBoxCompany")
        self.comboBoxCompany.setGeometry(QRect(10, 30, 121, 22))
        self.comboBoxModel = QComboBox(self.groupBoxRequired)
        self.comboBoxModel.setObjectName(u"comboBoxModel")
        self.comboBoxModel.setGeometry(QRect(140, 30, 166, 22))
        self.labelModel = QLabel(self.groupBoxRequired)
        self.labelModel.setObjectName(u"labelModel")
        self.labelModel.setGeometry(QRect(140, 10, 71, 16))
        self.comboBoxLocation = QComboBox(self.groupBoxRequired)
        self.comboBoxLocation.setObjectName(u"comboBoxLocation")
        self.comboBoxLocation.setGeometry(QRect(320, 30, 150, 22))
        self.labelLocation = QLabel(self.groupBoxRequired)
        self.labelLocation.setObjectName(u"labelLocation")
        self.labelLocation.setGeometry(QRect(320, 10, 151, 16))
        self.labelStatus = QLabel(self.groupBoxRequired)
        self.labelStatus.setObjectName(u"labelStatus")
        self.labelStatus.setGeometry(QRect(480, 10, 71, 16))
        self.comboBoxStatus = QComboBox(self.groupBoxRequired)
        self.comboBoxStatus.setObjectName(u"comboBoxStatus")
        self.comboBoxStatus.setGeometry(QRect(480, 30, 166, 22))
        self.labelSupplier = QLabel(self.groupBoxRequired)
        self.labelSupplier.setObjectName(u"labelSupplier")
        self.labelSupplier.setGeometry(QRect(660, 10, 71, 16))
        self.comboBoxSupplier = QComboBox(self.groupBoxRequired)
        self.comboBoxSupplier.setObjectName(u"comboBoxSupplier")
        self.comboBoxSupplier.setGeometry(QRect(660, 30, 166, 22))
        self.labelCompanyError = QLabel(self.groupBoxRequired)
        self.labelCompanyError.setObjectName(u"labelCompanyError")
        self.labelCompanyError.setGeometry(QRect(10, 50, 81, 16))
        self.labelModelError = QLabel(self.groupBoxRequired)
        self.labelModelError.setObjectName(u"labelModelError")
        self.labelModelError.setGeometry(QRect(140, 50, 71, 16))
        self.labelLocationError = QLabel(self.groupBoxRequired)
        self.labelLocationError.setObjectName(u"labelLocationError")
        self.labelLocationError.setGeometry(QRect(320, 50, 151, 16))
        self.labelStatusError = QLabel(self.groupBoxRequired)
        self.labelStatusError.setObjectName(u"labelStatusError")
        self.labelStatusError.setGeometry(QRect(480, 50, 71, 16))
        self.labelSupplierError = QLabel(self.groupBoxRequired)
        self.labelSupplierError.setObjectName(u"labelSupplierError")
        self.labelSupplierError.setGeometry(QRect(660, 50, 71, 16))
        self.groupBoxStatic = QGroupBox(self.centralwidget)
        self.groupBoxStatic.setObjectName(u"groupBoxStatic")
        self.groupBoxStatic.setGeometry(QRect(10, 70, 476, 241))
        self.labelField = QLabel(self.groupBoxStatic)
        self.labelField.setObjectName(u"labelField")
        self.labelField.setGeometry(QRect(15, 20, 78, 13))
        self.labelField.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelAssetName = QLabel(self.groupBoxStatic)
        self.labelAssetName.setObjectName(u"labelAssetName")
        self.labelAssetName.setGeometry(QRect(10, 40, 83, 13))
        self.labelAssetName.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelPurchaseDate = QLabel(self.groupBoxStatic)
        self.labelPurchaseDate.setObjectName(u"labelPurchaseDate")
        self.labelPurchaseDate.setGeometry(QRect(10, 70, 83, 13))
        self.labelPurchaseDate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelOrderNumber = QLabel(self.groupBoxStatic)
        self.labelOrderNumber.setObjectName(u"labelOrderNumber")
        self.labelOrderNumber.setGeometry(QRect(10, 100, 83, 13))
        self.labelOrderNumber.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelPurchaseCost = QLabel(self.groupBoxStatic)
        self.labelPurchaseCost.setObjectName(u"labelPurchaseCost")
        self.labelPurchaseCost.setGeometry(QRect(10, 130, 83, 13))
        self.labelPurchaseCost.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelWarranty = QLabel(self.groupBoxStatic)
        self.labelWarranty.setObjectName(u"labelWarranty")
        self.labelWarranty.setGeometry(QRect(10, 160, 83, 13))
        self.labelWarranty.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelNotes = QLabel(self.groupBoxStatic)
        self.labelNotes.setObjectName(u"labelNotes")
        self.labelNotes.setGeometry(QRect(10, 190, 83, 13))
        self.labelNotes.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelFill = QLabel(self.groupBoxStatic)
        self.labelFill.setObjectName(u"labelFill")
        self.labelFill.setGeometry(QRect(90, 20, 19, 13))
        self.labelFill.setAlignment(Qt.AlignCenter)
        self.checkBoxAssetName = QCheckBox(self.groupBoxStatic)
        self.checkBoxAssetName.setObjectName(u"checkBoxAssetName")
        self.checkBoxAssetName.setGeometry(QRect(95, 40, 16, 17))
        self.checkBoxPurchaseDate = QCheckBox(self.groupBoxStatic)
        self.checkBoxPurchaseDate.setObjectName(u"checkBoxPurchaseDate")
        self.checkBoxPurchaseDate.setGeometry(QRect(95, 70, 16, 17))
        self.checkBoxOrderNumber = QCheckBox(self.groupBoxStatic)
        self.checkBoxOrderNumber.setObjectName(u"checkBoxOrderNumber")
        self.checkBoxOrderNumber.setGeometry(QRect(95, 100, 16, 17))
        self.checkBoxPurchaseCost = QCheckBox(self.groupBoxStatic)
        self.checkBoxPurchaseCost.setObjectName(u"checkBoxPurchaseCost")
        self.checkBoxPurchaseCost.setGeometry(QRect(95, 130, 16, 17))
        self.checkBoxWarranty = QCheckBox(self.groupBoxStatic)
        self.checkBoxWarranty.setObjectName(u"checkBoxWarranty")
        self.checkBoxWarranty.setGeometry(QRect(95, 160, 16, 17))
        self.checkBoxNotes = QCheckBox(self.groupBoxStatic)
        self.checkBoxNotes.setObjectName(u"checkBoxNotes")
        self.checkBoxNotes.setGeometry(QRect(95, 190, 16, 17))
        self.labelData = QLabel(self.groupBoxStatic)
        self.labelData.setObjectName(u"labelData")
        self.labelData.setGeometry(QRect(115, 20, 47, 13))
        self.dateEditPurchaseDate = QDateEdit(self.groupBoxStatic)
        self.dateEditPurchaseDate.setObjectName(u"dateEditPurchaseDate")
        self.dateEditPurchaseDate.setGeometry(QRect(115, 70, 113, 22))
        self.dateEditPurchaseDate.setCalendarPopup(True)
        self.checkBoxAppend = QCheckBox(self.groupBoxStatic)
        self.checkBoxAppend.setObjectName(u"checkBoxAppend")
        self.checkBoxAppend.setGeometry(QRect(385, 40, 16, 17))
        self.lineEditAssetName = QLineEdit(self.groupBoxStatic)
        self.lineEditAssetName.setObjectName(u"lineEditAssetName")
        self.lineEditAssetName.setGeometry(QRect(115, 40, 268, 20))
        self.lineEditAssetNameAppend = QLineEdit(self.groupBoxStatic)
        self.lineEditAssetNameAppend.setObjectName(u"lineEditAssetNameAppend")
        self.lineEditAssetNameAppend.setGeometry(QRect(405, 40, 39, 20))
        self.lineEditOrderNumber = QLineEdit(self.groupBoxStatic)
        self.lineEditOrderNumber.setObjectName(u"lineEditOrderNumber")
        self.lineEditOrderNumber.setGeometry(QRect(115, 100, 113, 20))
        self.lineEditPurchaseCost = QLineEdit(self.groupBoxStatic)
        self.lineEditPurchaseCost.setObjectName(u"lineEditPurchaseCost")
        self.lineEditPurchaseCost.setGeometry(QRect(115, 130, 113, 20))
        self.lineEditWarranty = QLineEdit(self.groupBoxStatic)
        self.lineEditWarranty.setObjectName(u"lineEditWarranty")
        self.lineEditWarranty.setGeometry(QRect(115, 160, 113, 20))
        self.lineEditNotes = QLineEdit(self.groupBoxStatic)
        self.lineEditNotes.setObjectName(u"lineEditNotes")
        self.lineEditNotes.setGeometry(QRect(115, 190, 113, 20))
        self.labelAppend = QLabel(self.groupBoxStatic)
        self.labelAppend.setObjectName(u"labelAppend")
        self.labelAppend.setGeometry(QRect(335, 20, 118, 13))
        self.labelNameError = QLabel(self.groupBoxStatic)
        self.labelNameError.setObjectName(u"labelNameError")
        self.labelNameError.setGeometry(QRect(450, 50, 11, 13))
        palette = QPalette()
        brush = QBrush(QColor(255, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        self.labelNameError.setPalette(palette)
        self.labelPurchaseDateError = QLabel(self.groupBoxStatic)
        self.labelPurchaseDateError.setObjectName(u"labelPurchaseDateError")
        self.labelPurchaseDateError.setGeometry(QRect(235, 80, 11, 13))
        palette1 = QPalette()
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        self.labelPurchaseDateError.setPalette(palette1)
        self.labelOrderNumberError = QLabel(self.groupBoxStatic)
        self.labelOrderNumberError.setObjectName(u"labelOrderNumberError")
        self.labelOrderNumberError.setGeometry(QRect(235, 110, 11, 13))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        self.labelOrderNumberError.setPalette(palette2)
        self.labelPurchaseCostError = QLabel(self.groupBoxStatic)
        self.labelPurchaseCostError.setObjectName(u"labelPurchaseCostError")
        self.labelPurchaseCostError.setGeometry(QRect(235, 140, 11, 13))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        self.labelPurchaseCostError.setPalette(palette3)
        self.labelWarrantyError = QLabel(self.groupBoxStatic)
        self.labelWarrantyError.setObjectName(u"labelWarrantyError")
        self.labelWarrantyError.setGeometry(QRect(235, 170, 11, 13))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        self.labelWarrantyError.setPalette(palette4)
        self.labelNotesError = QLabel(self.groupBoxStatic)
        self.labelNotesError.setObjectName(u"labelNotesError")
        self.labelNotesError.setGeometry(QRect(235, 200, 11, 13))
        palette5 = QPalette()
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        self.labelNotesError.setPalette(palette5)
        self.labelNameError_7 = QLabel(self.groupBoxStatic)
        self.labelNameError_7.setObjectName(u"labelNameError_7")
        self.labelNameError_7.setGeometry(QRect(10, 220, 11, 13))
        palette6 = QPalette()
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette6.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        self.labelNameError_7.setPalette(palette6)
        self.label = QLabel(self.groupBoxStatic)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 218, 281, 16))
        self.groupBoxScannable = QGroupBox(self.centralwidget)
        self.groupBoxScannable.setObjectName(u"groupBoxScannable")
        self.groupBoxScannable.setGeometry(QRect(490, 70, 131, 101))
        self.checkBoxScanAssetTag = QCheckBox(self.groupBoxScannable)
        self.checkBoxScanAssetTag.setObjectName(u"checkBoxScanAssetTag")
        self.checkBoxScanAssetTag.setGeometry(QRect(90, 42, 16, 17))
        self.checkBoxScanSerial = QCheckBox(self.groupBoxScannable)
        self.checkBoxScanSerial.setObjectName(u"checkBoxScanSerial")
        self.checkBoxScanSerial.setGeometry(QRect(90, 72, 16, 17))
        self.labelScanField = QLabel(self.groupBoxScannable)
        self.labelScanField.setObjectName(u"labelScanField")
        self.labelScanField.setGeometry(QRect(20, 20, 61, 13))
        self.labelScanField.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelSerialNum = QLabel(self.groupBoxScannable)
        self.labelSerialNum.setObjectName(u"labelSerialNum")
        self.labelSerialNum.setGeometry(QRect(20, 70, 65, 20))
        self.labelSerialNum.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelScan = QLabel(self.groupBoxScannable)
        self.labelScan.setObjectName(u"labelScan")
        self.labelScan.setGeometry(QRect(80, 20, 32, 13))
        self.labelScan.setAlignment(Qt.AlignCenter)
        self.labelAssetTag = QLabel(self.groupBoxScannable)
        self.labelAssetTag.setObjectName(u"labelAssetTag")
        self.labelAssetTag.setGeometry(QRect(20, 40, 65, 20))
        self.labelAssetTag.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBoxCheckout = QGroupBox(self.centralwidget)
        self.groupBoxCheckout.setObjectName(u"groupBoxCheckout")
        self.groupBoxCheckout.setGeometry(QRect(490, 170, 351, 101))
        self.checkBoxCheckOutEnabled = QCheckBox(self.groupBoxCheckout)
        self.checkBoxCheckOutEnabled.setObjectName(u"checkBoxCheckOutEnabled")
        self.checkBoxCheckOutEnabled.setGeometry(QRect(10, 20, 120, 20))
        self.comboBoxCheckoutTo = QComboBox(self.groupBoxCheckout)
        self.comboBoxCheckoutTo.setObjectName(u"comboBoxCheckoutTo")
        self.comboBoxCheckoutTo.setGeometry(QRect(10, 70, 331, 22))
        self.comboBoxCheckOutType = QComboBox(self.groupBoxCheckout)
        self.comboBoxCheckOutType.addItem("")
        self.comboBoxCheckOutType.addItem("")
        self.comboBoxCheckOutType.addItem("")
        self.comboBoxCheckOutType.addItem("")
        self.comboBoxCheckOutType.setObjectName(u"comboBoxCheckOutType")
        self.comboBoxCheckOutType.setGeometry(QRect(10, 40, 69, 22))
        self.groupBoxCustom = QGroupBox(self.centralwidget)
        self.groupBoxCustom.setObjectName(u"groupBoxCustom")
        self.groupBoxCustom.setGeometry(QRect(10, 310, 831, 161))
        self.tabWidgetCustomFields = QTabWidget(self.groupBoxCustom)
        self.tabWidgetCustomFields.setObjectName(u"tabWidgetCustomFields")
        self.tabWidgetCustomFields.setGeometry(QRect(10, 20, 811, 121))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidgetCustomFields.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidgetCustomFields.addTab(self.tab_2, "")
        self.pushButtonRefresh = QPushButton(self.centralwidget)
        self.pushButtonRefresh.setObjectName(u"pushButtonRefresh")
        self.pushButtonRefresh.setGeometry(QRect(670, 80, 75, 46))
        self.pushButtonScan = QPushButton(self.centralwidget)
        self.pushButtonScan.setObjectName(u"pushButtonScan")
        self.pushButtonScan.setGeometry(QRect(760, 80, 75, 46))
        self.groupBoxScanning = QGroupBox(self.centralwidget)
        self.groupBoxScanning.setObjectName(u"groupBoxScanning")
        self.groupBoxScanning.setGeometry(QRect(10, 470, 831, 111))
        self.labelScanning = QLabel(self.groupBoxScanning)
        self.labelScanning.setObjectName(u"labelScanning")
        self.labelScanning.setGeometry(QRect(10, 20, 397, 33))
        font = QFont()
        font.setPointSize(18)
        self.labelScanning.setFont(font)
        self.lineEditScanning = QLineEdit(self.groupBoxScanning)
        self.lineEditScanning.setObjectName(u"lineEditScanning")
        self.lineEditScanning.setEnabled(True)
        self.lineEditScanning.setGeometry(QRect(10, 60, 400, 40))
        font1 = QFont()
        font1.setPointSize(22)
        self.lineEditScanning.setFont(font1)
        self.pushButtonNext = QPushButton(self.groupBoxScanning)
        self.pushButtonNext.setObjectName(u"pushButtonNext")
        self.pushButtonNext.setGeometry(QRect(420, 60, 64, 40))
        font2 = QFont()
        font2.setPointSize(9)
        self.pushButtonNext.setFont(font2)
        self.labelScanStatus = QLabel(self.groupBoxScanning)
        self.labelScanStatus.setObjectName(u"labelScanStatus")
        self.labelScanStatus.setGeometry(QRect(490, 60, 331, 33))
        self.labelScanStatus.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 850, 22))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Exit)

        self.retranslateUi(MainWindow)

        self.tabWidgetCustomFields.setCurrentIndex(0)
        self.pushButtonNext.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Snipe Assist", None))
        self.action_Exit.setText(QCoreApplication.translate("MainWindow", u"E&xit", None))
        self.action_Save.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
        self.groupBoxRequired.setTitle(QCoreApplication.translate("MainWindow", u"Required Items", None))
        self.labelCompany.setText(QCoreApplication.translate("MainWindow", u"Company:", None))
        self.labelModel.setText(QCoreApplication.translate("MainWindow", u"Model:", None))
        self.labelLocation.setText(QCoreApplication.translate("MainWindow", u"Location and Default Location:", None))
        self.labelStatus.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.labelSupplier.setText(QCoreApplication.translate("MainWindow", u"Supplier:", None))
        self.labelCompanyError.setText(QCoreApplication.translate("MainWindow", u"CompanyError", None))
        self.labelModelError.setText(QCoreApplication.translate("MainWindow", u"ModelError", None))
        self.labelLocationError.setText(QCoreApplication.translate("MainWindow", u"LocationError", None))
        self.labelStatusError.setText(QCoreApplication.translate("MainWindow", u"StatusError", None))
        self.labelSupplierError.setText(QCoreApplication.translate("MainWindow", u"SupplierError", None))
        self.groupBoxStatic.setTitle(QCoreApplication.translate("MainWindow", u"Static Items", None))
        self.labelField.setText(QCoreApplication.translate("MainWindow", u"Field  ", None))
        self.labelAssetName.setText(QCoreApplication.translate("MainWindow", u"Asset Name: ", None))
        self.labelPurchaseDate.setText(QCoreApplication.translate("MainWindow", u"Purchase Date: ", None))
        self.labelOrderNumber.setText(QCoreApplication.translate("MainWindow", u"Order Number: ", None))
        self.labelPurchaseCost.setText(QCoreApplication.translate("MainWindow", u"Purchase Cost: ", None))
        self.labelWarranty.setText(QCoreApplication.translate("MainWindow", u"Warranty: ", None))
        self.labelNotes.setText(QCoreApplication.translate("MainWindow", u"Notes: ", None))
        self.labelFill.setText(QCoreApplication.translate("MainWindow", u"Fill", None))
        self.checkBoxAssetName.setText("")
        self.checkBoxPurchaseDate.setText("")
        self.checkBoxOrderNumber.setText("")
        self.checkBoxPurchaseCost.setText("")
        self.checkBoxWarranty.setText("")
        self.checkBoxNotes.setText("")
        self.labelData.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.checkBoxAppend.setText("")
        self.labelAppend.setText(QCoreApplication.translate("MainWindow", u"Append and Increment", None))
        self.labelNameError.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.labelPurchaseDateError.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.labelOrderNumberError.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.labelPurchaseCostError.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.labelWarrantyError.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.labelNotesError.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.labelNameError_7.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Either disable entery or provide requested data.", None))
        self.groupBoxScannable.setTitle(QCoreApplication.translate("MainWindow", u"Scannable Items", None))
        self.checkBoxScanAssetTag.setText("")
        self.checkBoxScanSerial.setText("")
        self.labelScanField.setText(QCoreApplication.translate("MainWindow", u"Field  ", None))
        self.labelSerialNum.setText(QCoreApplication.translate("MainWindow", u"Serial Num: ", None))
        self.labelScan.setText(QCoreApplication.translate("MainWindow", u"Scan", None))
        self.labelAssetTag.setText(QCoreApplication.translate("MainWindow", u"Asset Tag: ", None))
        self.groupBoxCheckout.setTitle(QCoreApplication.translate("MainWindow", u"Check Out", None))
        self.checkBoxCheckOutEnabled.setText(QCoreApplication.translate("MainWindow", u"Enable Check Out:", None))
        self.comboBoxCheckOutType.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.comboBoxCheckOutType.setItemText(1, QCoreApplication.translate("MainWindow", u"User", None))
        self.comboBoxCheckOutType.setItemText(2, QCoreApplication.translate("MainWindow", u"Asset", None))
        self.comboBoxCheckOutType.setItemText(3, QCoreApplication.translate("MainWindow", u"Location", None))

        self.groupBoxCustom.setTitle(QCoreApplication.translate("MainWindow", u"CustomFields", None))
        self.tabWidgetCustomFields.setTabText(self.tabWidgetCustomFields.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.tabWidgetCustomFields.setTabText(self.tabWidgetCustomFields.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.pushButtonRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh Req\n"
"Items", None))
        self.pushButtonScan.setText(QCoreApplication.translate("MainWindow", u"Start\n"
"Scanning", None))
        self.groupBoxScanning.setTitle(QCoreApplication.translate("MainWindow", u"Scanning", None))
        self.labelScanning.setText(QCoreApplication.translate("MainWindow", u"labelScanning", None))
        self.lineEditScanning.setText("")
        self.pushButtonNext.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.labelScanStatus.setText(QCoreApplication.translate("MainWindow", u"labelScanStatus", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
    # retranslateUi

